sudo: required
services:
 - docker

before_install:
 - docker build -t hesteban/multi-docker-app -f ./client/Dockerfile.dev ./client

script:
 - docker run hesteban/multi-docker-app npm test -- --coverage

after_success:
 - docker build -t hesteban/multi-client ./client 
 - docker build -t hesteban/multi-nginx ./ningx
 - docker build -t hesteban/multi-server ./server
 - docker build -t hesteban/multi-worker ./worker
# Log in to tthe docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push hesteban/multi-client
- docker push hesteban/multi-nginx
- docker push hesteban/multi-server
- docker push hesteban/multi-worker
