sudo: required
services:
 - docker

before_install:
 - docker build -t hesteban/multi-docker-app -f ./client/Dockerfile.dev ./client

script:
 - docker run hesteban/multi-docker-app npm test -- --coverage

after_success:
 - docker build -t hesteban/multi-client ./client 
 - docker build -t hesteban/multi-nginx ./nginx
 - docker build -t hesteban/multi-server ./server
 - docker build -t hesteban/multi-worker ./worker
# Log in to tthe docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push hesteban/multi-client
 - docker push hesteban/multi-nginx
 - docker push hesteban/multi-server
 - docker push hesteban/multi-worker

deploy:
 provider: elasticbeanstalk
 region: eu-west-2
 app: multi-docker-app
 env: MultiDockerApp-env
 bucket_name: elasticbeanstalk-eu-west-2-688717546506
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
   secure: $AWS_SECRET_KEY
